######################## default configuration ####################
baseURL = "https://mialecozy.online/"
title = "Miale Cozy Spaces"
theme = "mialecozyspaces"
timeout = 300000

[build]
writeStats = true

[build.buildStats]
enable = true

[build.processing]
css = true
scss = true
js = true
html = true

[build.processing.sass]
enableSourceMap = false
outputStyle = "compressed"
includePaths = ["node_modules"]

[module]
[module.hugoVersion]
extended = true
min = "0.87.0"

[security.exec]
allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^node$', '^git$', '^sass$']
osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM)$']

[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

[minify]
minifyOutput = true

[minify.tdewolff.html]
keepWhitespace = false

[minify.tdewolff.css]
keepCSS2 = true

[minify.tdewolff.js]
keepVarNames = false

[minify.tdewolff.json]
keepNumbers = true

[minify.tdewolff.xml]
keepWhitespace = false

[assets]
disableFingerprinting = false

[assets.sass]
enableSourceMap = false
outputStyle = "compressed"
includePaths = ["node_modules"]

[assets.minify]
disableCSS = false
disableJS = false

[assets.optimization]
bundleCSS = true
bundleJS = true
minifyCSS = true
minifyJS = true
gzip = true

[imaging]
quality = 82
resampleFilter = "Lanczos"
anchor = "Smart"

[imaging.exif]
includeFields = ""
disableDate = true
disableLatLong = true

[caches]
[caches.getresource]
dir = ":resourceDir/_gen"
maxAge = "24h"

[caches.getjson]
dir = ":resourceDir/_gen"
maxAge = "24h"

[caches.images]
dir = ":resourceDir/_gen"
maxAge = "24h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "24h"

[server]
[[server.headers]]
for = "/images/*"
[server.headers.values]
Cache-Control = "public, max-age=31536000"

[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "monokai"

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

[pagination]
pagerSize = 6

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
social = "social"

[sitemap]
changefreq = "daily"
priority = 0.5
enableRobotsTXT = true
