############# English navigation ##############

# main menu
[[main]]
name = "About"
url = "about"
weight = 1

[[main]]
name = "Spaces"
weight = 2
hasChildren = true

[[main]]
parent = "Spaces"
name = "Bedroom"
url = "categories/bedroom/"
weight = 1

[[main]]
parent = "Spaces"
name = "Bathroom"
url = "categories/bathroom/"
weight = 2

[[main]]
parent = "Spaces"
name = "Reading Nooks"
url = "categories/reading-nooks/"
weight = 3

[[main]]
parent = "Spaces"
name = "Outdoor"
url = "categories/outdoor/"
weight = 4

[[main]]
parent = "Spaces"
name = "Living Room"
url = "categories/living-room/"
weight = 5

[[main]]
parent = "Spaces"
name = "Patio"
url = "categories/patio/"
weight = 6

[[main]]
parent = "Spaces"
name = "Balcony"
url = "categories/balcony/"
weight = 7

[[main]]
parent = "Spaces"
name = "Kitchen"
url = "categories/kitchen/"
weight = 8

[[main]]
parent = "Spaces"
name = "Dining"
url = "categories/dining/"
weight = 9

[[main]]
name = "Shop"
url = "shop"
weight = 3


# offcanvas menu
[[offcanvas]]
name = "About"
url = "about"
weight = 1

[[offcanvas]]
name = "Spaces"
weight = 2
hasChildren = true

[[offcanvas]]
parent = "Spaces"
name = "Bedroom"
url = "categories/bedroom/"
weight = 1

[[offcanvas]]
parent = "Spaces"
name = "Bathroom"
url = "categories/bathroom/"
weight = 2

[[offcanvas]]
parent = "Spaces"
name = "Reading Nooks"
url = "categories/reading-nooks/"
weight = 3

[[offcanvas]]
parent = "Spaces"
name = "Outdoor"
url = "categories/outdoor/"
weight = 4

[[offcanvas]]
parent = "Spaces"
name = "Living Room"
url = "categories/living-room/"
weight = 5

[[offcanvas]]
parent = "Spaces"
name = "Patio"
url = "categories/patio/"
weight = 6

[[offcanvas]]
parent = "Spaces"
name = "Balcony"
url = "categories/balcony/"
weight = 7

[[offcanvas]]
parent = "Spaces"
name = "Kitchen"
url = "categories/kitchen/"
weight = 8

[[offcanvas]]
parent = "Spaces"
name = "Dining"
url = "categories/dining/"
weight = 9

[[offcanvas]]
name = "Shop"
url = "shop"
weight = 3


# footer menu
[[footer]]
name = "facebook"
URL = "/"
weight = 1

[[footer]]
name = "instagram"
URL = "/"
weight = 2

[[footer]]
name = "twitter"
URL = "/"
weight = 3
